### ISSUE TITLE
Error in ensureDomainExistence function: "Decode data for discriminant 85 is undefined"

### ISSUE THREAD

**Issue by 6r1d** [hyperledger/iroha-javascript#126]
Today, Youssef Mohammad [reported](https://t.me/hyperledgeriroha/24516) an error occuring with Iroha-JS in Iroha Telegram.

<details>
  <summary>Log</summary>

  ```text
js
file:///C:/Users/ASUS/Desktop/crowd-funding/node_modules/@scale-codec/core/dist/lib.mjs:583
    throw new Error(`Decode data for discriminant ${discriminant} is undefined; decoders schema: ${formatDecoders(decoders)}`);
          ^

Error: Decode data for discriminant 85 is undefined; decoders schema: 0 => Decode(...), 1 => Signature(...), 2 => Permission(...), 3 => Evaluate(...), 4 => Find(...), 5 => Conversion(...)
    at decodeEnum (file:///C:/Users/ASUS/Desktop/crowd-funding/node_modules/@scale-codec/core/dist/lib.mjs:583:11)
    at file:///C:/Users/ASUS/Desktop/crowd-funding/node_modules/@scale-codec/core/dist/lib.mjs:590:22
    at trackDecode (file:///C:/Users/ASUS/Desktop/crowd-funding/node_modules/@scale-codec/definition-runtime/dist/lib.mjs:19:61)
    at decodeTracked (file:///C:/Users/ASUS/Desktop/crowd-funding/node_modules/@scale-codec/definition-runtime/dist/lib.mjs:238:37)
    at WalkerImpl.decode (file:///C:/Users/ASUS/Desktop/crowd-funding/node_modules/@scale-codec/core/dist/lib.mjs:16:19)
    at Function.fromBuffer (file:///C:/Users/ASUS/Desktop/crowd-funding/node_modules/@scale-codec/definition-runtime/dist/lib.mjs:243:37)
    at Client.request (file:///C:/Users/ASUS/Desktop/crowd-funding/node_modules/@iroha2/client/dist/lib.mjs:350:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ensureDomainExistence (file:///C:/Users/ASUS/Desktop/crowd-funding/client.js:120:18)
    at async file:///C:/Users/ASUS/Desktop/crowd-funding/client.js:136:1

Node.js v18.9.0
  ```
</details>

Details [reported](https://t.me/hyperledgeriroha/24520):

* A bare-metal version of Iroha
* [`iroha2-stable`](https://github.com/hyperledger/iroha/tree/iroha2-stable) branch
* Git commit hash for Iroha: [`eec85ce9`](https://github.com/hyperledger/iroha/commit/eec85ce9)
* `@iroha2/client` ver. 2.0.2
* Distro running Iroha peer(s): Ubuntu 20.04.5 LTS
* Distro running the client: Windows 10
* `uname -a` output: Linux Hyper 5.4.0-125-generic #141-Ubuntu SMP Wed Aug 10 13:42:03 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by 6r1d** [comment]
Youssef also reported a decoded error: `Unhandled rejection: WarpQueryError(Decode(ParityScale))`.

It was displayed by modifying a file: `node_modules\@iroha2\client\dist\lib.mjs`

Currently, I have a screenshot of the changed code and requested the text:

![photo1663672644](https://user-images.githubusercontent.com/2552837/191246386-d3b7f2a2-44fd-4179-a326-89147d27ca85.jpeg)

**Comment by 0x009922** [comment]
@6r1d, please mention me directly and add `iroha2` label to the issue so it can be more accessible for my attention. Thanks.

In general, I think it is a versioning issue. `@iroha2/client` and `@iroha2/data-model` `v2.0.2` targets Iroha 2 RC6 (previous LTS): https://github.com/hyperledger/iroha/commit/75da907f66d5270f407a50e06bc76cec41d3d409.

I am not sure that `iroha2-stable` is the same.

**Comment by 6r1d** [comment]
Sure, but hopefully it will not repeat. I am not sure personally, so it would help if you explain a bit.

**Comment by 0x009922** [comment]
I think it is simply a compatibility issue.

However, I think it might be useful to implement this:

- https://github.com/hyperledger/iroha-javascript/issues/147
